# Sim builder
rng_seed: 0
author_fraction_of_private_blocks: 0.0
institution_num_blocks: 10
author_response_time_mean: 5
author_response_time_sigma: 3
buyer_max_budget_mean: 8
buyer_max_budget_sigma: 0
buyer_urgency_min: 20
buyer_urgency_max: 21
query_creation_time_start: 0
query_creation_time_end: 1
embedding_manager_path: "data/final_dataset_embeddings.db"
dataset_path: "data/final_dataset_with_metadata.json"
query_range: "general_questions:51"
fraction_active_vendors: 1.0

# Simulator
buyer_agent_kwargs:
  quote_review_top_k: 3
  quote_review_use_block_metadata: true
  num_quote_gathering_steps: 2
  max_query_depth: 2
  use_reranker: true
  reranker_max_num_quotes: 50
vendor_agent_kwargs:
  retriever_config:
    filter_with_bm25: true
    bm25_top_k: 30
    bm25_score_threshold: 0.5
    bm25_use_caching: true
    bm25_weight: 0.0
    filter_with_mips: true
    mips_use_hyde: true
    mips_top_k: 10
    mips_score_threshold: 0.8
    mips_half_sphere: true
    mips_embed_block_content_with_metadata: true
    mips_weight: 1.0
bulletin_board_retrieval_top_k: 1
bulletin_board_retrieval_score_threshold: 0.7
llm_name: "gpt-4"
embedding_name: "bge-large-en"
reranker_name: "ms-marco-MiniLM-L-12-v2"

# LLAMAPI
LLAMAPI_API_PORT: 8911
LLAMAPI_API_HOST: "http://login-1:8911"
