rng_seed: 0
author_block_price_mean: 5
author_block_price_sigma: 3
institution_block_price_mean: 5
institution_block_price_sigma: 3
author_fraction_of_private_blocks: 0.5
institution_num_blocks: 10
author_response_time_mean: 5
author_response_time_sigma: 3
buyer_max_budget_mean: 5
buyer_max_budget_sigma: 3
buyer_urgency_min: 1
buyer_urgency_max: 10
buyer_agent_kwargs:
  quote_review_top_k: 3
  quote_review_use_block_metadata: true
  num_quote_gathering_steps: 2
  use_reranker: true
vendor_agent_kwargs:
  retriever_config:
    filter_with_bm25: true
    bm25_top_k: 30
    bm25_score_threshold: 0.1
    bm25_use_caching: true
    bm25_weight: 0.0
    filter_with_mips: true
    mips_use_hyde: false
    mips_top_k: 10
    mips_score_threshold: 0.7
    mips_half_sphere: true
    mips_embed_block_content_with_metadata: true
    mips_weight: 1.0
query_creation_time_start: 0
query_creation_time_end: 168
bulletin_board_retrieval_top_k: 1
bulletin_board_retrieval_score_threshold: 0.7
llm_name: "gpt-3.5-turbo-16k"
embedding_name: "bge-large-en"